package com.darmisolutions.darmihire.security;

public enum Permission {
    MANAGE_TENANT,
    MANAGE_USERS,
    MANAGE_DEPARTMENTS,
    MANAGE_TEAMS,
    MANAGE_LOCATIONS,
    MANAGE_JOBS,
    MANAGE_CANDIDATES,
    MANAGE_APPLICATIONS,
    MANAGE_INTERVIEWS,
    COMPANY_ADMIN,
    RECRUITER,
    VIEW_INTERVIEWS,
    SUBMIT_INTERVIEW_FEEDBACK
}