version: "3.8"
services:
  react-app:
    container_name: node-typescript-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
