'use client';
import { FormEvent, useState } from 'react';

type Profile={headline?:string;title?:string;years_experience?:number|null;minimum_years_experience?:number|null;preferred_skills?:string[]};
type Result={match_score:number;overall_score:number;keyword_score:number;semantic_score:number|null;matched_skills:string[];missing_skills:string[];resume_skills:string[];job_skills:string[];summary:string;ai_enabled:boolean;ai_explanation:string;strengths:string[];gaps:string[];recommendations:string[];resume_profile:Profile|null;job_profile:Profile|null};
export default function Home(){
 const [file,setFile]=useState<File|null>(null),[job,setJob]=useState(''),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setResult(null);if(!file){setError('Choose a PDF or DOCX resume.');return;}setLoading(true);const fd=new FormData();fd.append('resume',file);fd.append('job_description',job);try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'}/api/analyze`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Analysis failed');setResult(data)}catch(e){setError(e instanceof Error?e.message:'Analysis failed')}finally{setLoading(false)}}
 return <main><header><span className="brand">ResumeMatch AI</span><span className="badge">Phase 2 · AI enhanced</span></header><section className="hero"><p className="eyebrow">RESUME + JOB MATCHING SYSTEM</p><h1>Understand the match,<br/>not just the keywords.</h1><p>Structured AI extraction, deterministic skill coverage and embedding similarity combine into an explainable job-match report.</p></section><form onSubmit={submit} className="grid"><div className="card"><h2>1. Resume</h2><label className="upload"><strong>{file?file.name:'Drop or choose your resume'}</strong><span>PDF or DOCX · max 5 MB</span><input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="card"><h2>2. Job description</h2><textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the complete job description here..." required/><button disabled={loading}>{loading?'Running AI analysis…':'Analyze with AI →'}</button></div></form>{error&&<p className="error">{error}</p>}{result&&<section className="results"><div className="score"><span>{result.overall_score}%</span><div><h2>Overall match</h2><p>{result.summary}</p><small>{result.ai_enabled?'AI features enabled':'Fallback mode — configure OPENAI_API_KEY for Phase 2 AI'}</small></div></div><div className="metrics"><Metric label="Skill coverage" value={`${result.keyword_score}%`}/><Metric label="Semantic similarity" value={result.semantic_score===null?'—':`${result.semantic_score}%`}/><Metric label="Matched skills" value={`${result.matched_skills.length}/${result.job_skills.length}`}/></div><div className="resultGrid"><Skill title="Matched skills" items={result.matched_skills} kind="match"/><Skill title="Missing skills" items={result.missing_skills} kind="missing"/></div>{result.ai_enabled&&<><div className="card insight"><h2>AI explanation</h2><p>{result.ai_explanation}</p></div><div className="triple"><ListCard title="Strengths" items={result.strengths}/><ListCard title="Gaps" items={result.gaps}/><ListCard title="Recommendations" items={result.recommendations}/></div></>}<details><summary>Structured extraction</summary>{result.resume_profile&&<p><b>Resume:</b> {result.resume_profile.headline||'Candidate'}{result.resume_profile.years_experience!=null?` · ${result.resume_profile.years_experience} years`:''}</p>}{result.job_profile&&<p><b>Role:</b> {result.job_profile.title||'Not detected'}{result.job_profile.minimum_years_experience!=null?` · ${result.job_profile.minimum_years_experience}+ years required`:''}</p>}<p><b>Resume skills:</b> {result.resume_skills.join(', ')||'None'}</p><p><b>Required job skills:</b> {result.job_skills.join(', ')||'None'}</p></details></section>}</main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Skill({title,items,kind}:{title:string;items:string[];kind:string}){return <div className="card"><h2>{title}</h2><div className="chips">{items.length?items.map(x=><span className={kind} key={x}>{kind==='match'?'✓':'!'} {x}</span>):<p>None detected</p>}</div></div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="card"><h2>{title}</h2>{items.length?<ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None</p>}</div>}
