'use client';
import { FormEvent, useState } from 'react';

type Result={match_score:number;matched_skills:string[];missing_skills:string[];resume_skills:string[];job_skills:string[];summary:string};
export default function Home(){
 const [file,setFile]=useState<File|null>(null),[job,setJob]=useState(''),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setResult(null);if(!file){setError('Choose a PDF or DOCX resume.');return;}setLoading(true);const fd=new FormData();fd.append('resume',file);fd.append('job_description',job);try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'}/api/analyze`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Analysis failed');setResult(data)}catch(e){setError(e instanceof Error?e.message:'Analysis failed')}finally{setLoading(false)}}
 return <main><header><span className="brand">ResumeMatch</span><span className="badge">Phase 1 · deterministic MVP</span></header><section className="hero"><p className="eyebrow">RESUME + JOB MATCHING SYSTEM</p><h1>See how well your resume<br/>matches the role.</h1><p>Upload your resume, paste a job description, and get an explainable skill match in seconds.</p></section><form onSubmit={submit} className="grid"><div className="card"><h2>1. Resume</h2><label className="upload"><strong>{file?file.name:'Drop or choose your resume'}</strong><span>PDF or DOCX · max 5 MB</span><input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="card"><h2>2. Job description</h2><textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the complete job description here..." required/><button disabled={loading}>{loading?'Analyzing…':'Analyze match →'}</button></div></form>{error&&<p className="error">{error}</p>}{result&&<section className="results"><div className="score"><span>{result.match_score}%</span><div><h2>Overall skill match</h2><p>{result.summary}</p></div></div><div className="resultGrid"><Skill title="Matched skills" items={result.matched_skills} kind="match"/><Skill title="Missing skills" items={result.missing_skills} kind="missing"/></div><details><summary>Detected skills</summary><p><b>Resume:</b> {result.resume_skills.join(', ')||'None'}</p><p><b>Job:</b> {result.job_skills.join(', ')||'None'}</p></details></section>}</main>
}
function Skill({title,items,kind}:{title:string;items:string[];kind:string}){return <div className="card"><h2>{title}</h2><div className="chips">{items.length?items.map(x=><span className={kind} key={x}>{kind==='match'?'✓':'!'} {x}</span>):<p>None detected</p>}</div></div>}
